"""add emag category id field to the mappings table

Revision ID: c807c65ae200
Revises: 
Create Date: 2025-04-23 16:57:09.194864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c807c65ae200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emag_category_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.drop_column('emag_category_id')

    # ### end Alembic commands ###
